### PR TITLE
Updated features with Google site examples

### PR DESCRIPTION
**Pull request by gliptak**
#3 If you like, I can update the master with the generated site.

### CODE REVIEW

**Comment by gliptak** [comment]
@mperry Please review. Thanks

**Comment by tonymorris** [comment]
:+1:

**Comment by gliptak** [comment]
@mperry Are you OK with publishing this or should I go ahead? Thanks

**Comment by mperry** [comment]
I will take a look in the next 24 hours.

**Comment by mperry** [comment]
@gliptak Should this be on the examples-java8.adoc page rather than the list of features?

**Comment by gliptak** [comment]
These seem to work well as initial highlights of features, that is why I added to features.

**Comment by gliptak** [comment]
@mperry Are you good with updating the features?

**Comment by gliptak** [comment]
Would you like me to merge this (and publish to ```main```)? Thanks

**Comment by gliptak** [comment]
I merged the changes and ```publish```ed them. Thanks

**Pull request closed without merging**
